#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tubeLoadNative.Droid.Resource", IsApplication=true)]

namespace tubeLoadNative.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int brightassets = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int darkassets = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_media_next = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_media_pause = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_media_play = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_media_previous = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_media_stop = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int splashimg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int youtubeic2 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080019
			public const int addSong = 2131230745;
			
			// aapt resource value: 0x7f08000c
			public const int channelName = 2131230732;
			
			// aapt resource value: 0x7f08001a
			public const int currentSong = 2131230746;
			
			// aapt resource value: 0x7f08000d
			public const int downloadBtn = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int item_delete = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int item_play = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int item_rename = 2131230749;
			
			// aapt resource value: 0x7f080006
			public const int linearLayout1 = 2131230726;
			
			// aapt resource value: 0x7f080012
			public const int linearLayout2 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int linearLayout3 = 2131230739;
			
			// aapt resource value: 0x7f080018
			public const int mySong = 2131230744;
			
			// aapt resource value: 0x7f080009
			public const int nextBtn = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int playBtn = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int prevBtn = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int searchBtn = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int searchEditText = 2131230734;
			
			// aapt resource value: 0x7f080015
			public const int seekBar = 2131230741;
			
			// aapt resource value: 0x7f08001e
			public const int seek_bar = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int seekbar = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int songImg = 2131230720;
			
			// aapt resource value: 0x7f080017
			public const int songLength = 2131230743;
			
			// aapt resource value: 0x7f080011
			public const int songName = 2131230737;
			
			// aapt resource value: 0x7f080016
			public const int songPosition = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int songTitle = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int songsListView = 2131230736;
			
			// aapt resource value: 0x7f080001
			public const int space1 = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int space2 = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int space3 = 2131230723;
			
			// aapt resource value: 0x7f080014
			public const int videoChannelName = 2131230740;
			
			// aapt resource value: 0x7f08000a
			public const int videoImg = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int videoName = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_current_song = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_download_song = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_search_songs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_songs_player = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int adapter_songs = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int adapter_videos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int view_seekbar = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int song_actions_menu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
