#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("tubeLoadNative.Droid.Resource", IsApplication=true)]

namespace tubeLoadNative.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int adSize = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int adSizes = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int adUnitId = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int brightassets = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_light = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_tint = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int darkassets = 2131099656;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int default_song_image = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_disabled_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int googleg_standard_color_18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_cancel_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_download = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_downloading = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_media_next = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_media_pause = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_media_play = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_media_play_pause = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_media_previous = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_media_stop = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_play_pause = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int icon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int selector = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int splashimg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int youtubeic2 = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090019
			public const int adView = 2131296281;
			
			// aapt resource value: 0x7f090029
			public const int addSong = 2131296297;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f09002c
			public const int alphabeticSort = 2131296300;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f090015
			public const int channelName = 2131296277;
			
			// aapt resource value: 0x7f09001b
			public const int clearBtn = 2131296283;
			
			// aapt resource value: 0x7f090024
			public const int closeBtn = 2131296292;
			
			// aapt resource value: 0x7f09002a
			public const int currentSong = 2131296298;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090016
			public const int downloadBtn = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int downloadingProgressBar = 2131296279;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f09002f
			public const int item_delete = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int item_play = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int item_rename = 2131296305;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f09000f
			public const int linearLayout1 = 2131296271;
			
			// aapt resource value: 0x7f09001f
			public const int linearLayout2 = 2131296287;
			
			// aapt resource value: 0x7f09002d
			public const int modifiedSort = 2131296301;
			
			// aapt resource value: 0x7f090028
			public const int mySong = 2131296296;
			
			// aapt resource value: 0x7f090012
			public const int nextBtn = 2131296274;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090023
			public const int notificationContent = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int notificationTitle = 2131296290;
			
			// aapt resource value: 0x7f09002b
			public const int orderSongs = 2131296299;
			
			// aapt resource value: 0x7f090011
			public const int playBtn = 2131296273;
			
			// aapt resource value: 0x7f090010
			public const int prevBtn = 2131296272;
			
			// aapt resource value: 0x7f090018
			public const int relativeLayout1 = 2131296280;
			
			// aapt resource value: 0x7f090021
			public const int searchActivityDownloadButton = 2131296289;
			
			// aapt resource value: 0x7f09001c
			public const int searchBtn = 2131296284;
			
			// aapt resource value: 0x7f09001a
			public const int searchEditText = 2131296282;
			
			// aapt resource value: 0x7f090025
			public const int seekBar = 2131296293;
			
			// aapt resource value: 0x7f090032
			public const int seek_bar = 2131296306;
			
			// aapt resource value: 0x7f09000d
			public const int seekbar = 2131296269;
			
			// aapt resource value: 0x7f090009
			public const int songImg = 2131296265;
			
			// aapt resource value: 0x7f090027
			public const int songLength = 2131296295;
			
			// aapt resource value: 0x7f09001e
			public const int songName = 2131296286;
			
			// aapt resource value: 0x7f090026
			public const int songPosition = 2131296294;
			
			// aapt resource value: 0x7f09000b
			public const int songTitle = 2131296267;
			
			// aapt resource value: 0x7f09001d
			public const int songsListView = 2131296285;
			
			// aapt resource value: 0x7f09000a
			public const int space1 = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public const int space2 = 2131296270;
			
			// aapt resource value: 0x7f09000c
			public const int space3 = 2131296268;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f09002e
			public const int suffleSongs = 2131296302;
			
			// aapt resource value: 0x7f090020
			public const int videoChannelName = 2131296288;
			
			// aapt resource value: 0x7f090013
			public const int videoImg = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int videoName = 2131296276;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_current_song = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_download_song = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_search_songs = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_songs_player = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int adapter_songs = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int adapter_videos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int view_notification_actions = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int view_seekbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int song_actions_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050011
			public const int accept = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int app_name = 2131034139;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int create_calendar_message = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int create_calendar_title = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int debug_menu_ad_information = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int debug_menu_creative_preview = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int debug_menu_title = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int debug_menu_troubleshooting = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int decline = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int store_picture_message = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int store_picture_title = 2131034138;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyTheme_Splash = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
